'use strict';

module.exports = {
    REQUEST_TRACK: 'REQUEST_TRACK',
    REQUEST_TRACK_SUCCESS: 'REQUEST_TRACK_SUCCESS',
    REQUEST_TRACK_ERROR: 'REQUEST_TRACK_ERROR',

    REQUEST_SEARCH: 'REQUEST_SEARCH',
    REQUEST_SEARCH_SUCCESS: 'REQUEST_SEARCH_SUCCESS',
    REQUEST_SEARCH_ERROR: 'REQUEST_SEARCH_ERROR',

    REQUEST_QUEUE: 'REQUEST_QUEUE',
    REQUEST_QUEUE_SUCCESS: 'REQUEST_QUEUE_SUCCESS',
    REQUEST_QUEUE_ERROR: 'REQUEST_QUEUE_ERROR',

    VOTE_TRACK_ERROR: 'VOTE_TRACK_ERROR',
    VOTE_TRACK_SUCCESS: 'VOTE_TRACK_SUCCESS',

    REQUEST_USER_ERROR: 'REQUEST_USER_ERROR',
    REQUEST_USER_SUCCESS: 'REQUEST_USER_SUCCESS',

    TRACK_CHANGE: 'TRACK_CHANGE',
    TRACK_POSITION: 'TRACK_POSITION',

    ENTITIES_UPDATE: 'ENTITIES_UPDATE',
    RELATED_TRACKS: 'RELATED_TRACKS',

    WAVEFORM_DATA: 'WAVEFORM_DATA'
};